INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('paulaSE@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(count, image, score, title) VALUES (2,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg',4.5, 'The Witcher');
INSERT INTO tb_movie(count, image, score, title) VALUES (3,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg',3.3,  'Venom: Tempo de Carnificina');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/u7SeO6Y42P7VCTWLhpnL96cyOqd.jpg', 0, 'O Espetacular Homem-Aranha 2: A Ameaça de Electro');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hv7o3VgfsairBoQFAawgaQ4cR1m.jpg', 0, 'Matrix Resurrections');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cinER0ESG0eJ49kXlExM0MEWGxW.jpg', 0, 'Shang-Chi e a Lenda dos Dez Anéis');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg', 0, 'Django Livre');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yDI6D5ZQh67YU4r2ms8qcSbAviZ.jpg', 0, 'Titanic');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cWUOv3H7YFwvKeaQhoAQTLLpo9Z.jpg', 0, 'O Lobo de Wall Street');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jiqD14fg7UTZOT6qgvzTmfRYpWI.jpg', 0, 'Aves de Rapina: Arlequina e sua Emancipação Fantabulosa');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6t8ES1d12OzWyCGxBeDYLHoaDrT.jpg', 0, 'Rogue One: Uma História Star Wars');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/uK15I3sGd8AudO9z6J6vi0HH1UU.jpg', 0, 'Star Wars: A Guerra dos Clones');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/36LnijfQCOC89rCMOhn2OINXROI.jpg', 0, 'Star Wars: Episódio I - A Ameaça Fantasma');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg', 0, 'Vingadores: Ultimato');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cDJ61O1STtbWNBwefuqVrRe3d7l.jpg', 0, 'Thor');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hqh5O4KssfJWI62HGAgrjHXbxhD.jpg', 0, 'Cisne Negro');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mfwq2nMBzArzQ7Y9RKE8SKeeTkg.jpg', 0, 'O Silêncio dos Inocentes');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hZkgoQYus5vegHoetLkCJzb17zJ.jpg', 0, 'Clube da Luta');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/31VpBgUX5O4Z3dn5ZbX8HLqoXH3.jpg', 0, 'Guerra Mundial Z');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vcrgU0KaNj5mKUCIQSUdiQwTE9y.jpg', 0, 'Harry Potter e as Relíquias da Morte - Parte 1');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lvOLivVeX3DVVcwfVkxKf0R22D8.jpg', 0, 'Harry Potter e a Pedra Filosofal');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qNdlZgz9yoSJ8f0YxQWfKGPoVV.jpg',  0, 'Alice no País das Maravilhas');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/8Qsr8pvDL3s1jNZQ4HK1d1Xlvnh.jpg', 0, 'Animais Fantásticos e Onde Habitam');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kq2MHrRfH6RTfkvyDEmYLmGHE6U.jpg', 0, 'A Teoria de Tudo');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/sjx6zjQI2dLGtEL0HGWsnq6UyLU.jpg', 0, 'O Livro de Boba Fett');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4LrL40XecjGLRpX5I2gzMTUt04l.jpg', 0, 'O Último Duelo');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg', 0, 'Interestelar');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yFkUPqBuUnbhYbQL8VFpTrAT9za.jpg', 0, 'Contato');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg', 0, 'Duna');
INSERT INTO tb_movie(count, image, score, title) VALUES (0,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2cUsDz4TzFYHrKktT1bKHHQ7Cgm.jpg', 0, 'Aquaman');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);